import proforma.ProFormaForm as ProFormaForm
from statistics import mean

myUnits = mean([900,1000,1500]) #unit in sqft

# name: type, sqft, rent
myAMI = { "Coliving Extra-Affordable": ['Coliving', 0.1, 325, 590],
          "Studio Extra-Affordable": ['Studio', 0.01, 400, 700],
          "1-Bed Extra-Affordable": ['1-Bed', 0.012, 400, 750],
          "2-Bed Extra-Affordable": ['2-Bed', 0.253, 600, 900],
          "3-Bed Extra-Affordable": ['3-Bed', 0.085, 600, 1040],
          "Coliving Affordable": ['Coliving', 0.1, 325, 1301],
          "Studio Affordable": ['Studio', 0.07, 400, 1593],
          "1-Bed Affordable": ['1-Bed', 0.05, 600, 1626],
          "2-Bed Affordable": ['2-Bed', 0.02, 900, 1951],
          "3-Bed Affordable": ['3-Bed', 0.01, 1175, 2255],
          "Coliving Market": ['Coliving', 0.2, 325, 2302],
          "Studio Market": ['Studio', 0.2, 400, 2782],
          "1-Bed Market": ['1-Bed', 0.2, 600, 2982],
          "2-Bed Market": ['2-Bed', 0.1, 900, 3578],
          "3-Bed Market": ['3-Bed', 0.05, 1175, 4133]
}

#

# #Air rights: Carver
# myProForma = ProFormaForm.ProForma(verbose= False,
#                                    exportToExcel= False,
#                                    yrs = 20,
#                                    start_year = 2022,
#                                    lot_area=637132,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    landscape_gross_sqft= 580382,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft=2418688,
#                                    commercial_gross_sqft=558159,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=372106,
#                                    avgUnitSize_residential=680,
#                                    avgUnitSize_commercial=8600,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=10550,
#                                    residential_cost=470,
#                                    residential_rent=2450,
#                                    commercial_cost=400,
#                                    commercial_rent=322500,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=400,
#                                    community_rent=263750,
#                                    hard_cost=315,
#                                    soft_cost=135,
#                                    land_cost=0,
#                                    landscape_cost= 35,
#                                    residential_AMI=myAMI)

# #Air rights: Carver One Building
# myProForma = ProFormaForm.ProForma(verbose= False,
#                                    exportToExcel= False,
#                                    yrs = 20,
#                                    start_year = 2022,
#                                    lot_area=0,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    landscape_gross_sqft= 0,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft=213821,
#                                    commercial_gross_sqft=49343,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=32896,
#                                    avgUnitSize_residential=573,
#                                    avgUnitSize_commercial=8600,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=10550,
#                                    residential_cost=470,
#                                    residential_rent=1899,
#                                    commercial_cost=400,
#                                    commercial_rent=322500,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=400,
#                                    community_rent=263750,
#                                    hard_cost=315,
#                                    soft_cost=135,
#                                    land_cost=0,
#                                    landscape_cost= 35,
#                                    residential_AMI=myAMI)


# #Air rights: Carver Phase 1
# myProForma = ProFormaForm.ProForma(verbose= False,
#                                    exportToExcel= False,
#                                    yrs = 5,
#                                    start_year = 2022,
#                                    lot_area=637132,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    landscape_gross_sqft=0,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft=142727,
#                                    commercial_gross_sqft=27186,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=22655,
#                                    avgUnitSize_residential=573,
#                                    avgUnitSize_commercial=8600,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=10550,
#                                    residential_cost=470,
#                                    residential_rent=1899,
#                                    commercial_cost=400,
#                                    commercial_rent=322500,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=400,
#                                    community_rent=263750,
#                                    hard_cost=280,
#                                    soft_cost=120,
#                                    land_cost=1,
#                                    landscape_cost=0,
#                                    residential_AMI=myAMI)

# #Air rights: Carver Phase 2
# myProForma = ProFormaForm.ProForma(verbose= False,
#                                    exportToExcel= False,
#                                    yrs = 4,
#                                    start_year = 2027,
#                                    lot_area=637132,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    landscape_gross_sqft= 580382,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft=70270,
#                                    commercial_gross_sqft=9821,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=6953,
#                                    avgUnitSize_residential=573,
#                                    avgUnitSize_commercial=8600,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=10550,
#                                    residential_cost=350,
#                                    residential_rent=1899,
#                                    commercial_cost=350,
#                                    commercial_rent=322500,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=350,
#                                    community_rent=263750,
#                                    hard_cost=245,
#                                    soft_cost=105,
#                                    land_cost=1,
#                                    landscape_cost= 0,
#                                    residential_AMI=myAMI)

#Air rights: Carver Phase 3
myProForma = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 4,
                                   start_year = 2031,
                                   lot_area=637132,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 580382,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft=0,
                                   commercial_gross_sqft=12366,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft=3290,
                                   avgUnitSize_residential=573,
                                   avgUnitSize_commercial=8600,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community=10550,
                                   residential_cost=0,
                                   residential_rent=0,
                                   commercial_cost=400,
                                   commercial_rent=322500,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost=400,
                                   community_rent=263750,
                                   hard_cost=280,
                                   soft_cost=120,
                                   land_cost=1,
                                   landscape_cost= 35,
                                   residential_AMI=myAMI)

# #Air rights: NYCHA
# myProForma = ProFormaForm.ProForma(verbose= False,
#                                    exportToExcel= False,
#                                    yrs = 20,
#                                    start_year = 2022,
#                                    lot_area=957329044,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    landscape_gross_sqft=0,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft=198651729,
#                                    commercial_gross_sqft=45842707,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=30561804,
#                                    avgUnitSize_residential=680,
#                                    avgUnitSize_commercial=8600,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=10550,
#                                    residential_cost=470,
#                                    residential_rent=2450,
#                                    commercial_cost=400,
#                                    commercial_rent=322500,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=400,
#                                    community_rent=263750,
#                                    hard_cost=315,
#                                    soft_cost=135,
#                                    land_cost=0,
#                                    landscape_cost= 35,
#                                    residential_AMI=myAMI)

# myProForma = ProFormaForm.ProForma(verbose= True,
#                                    exportToExcel= False,
#                                    yrs = 10,
#                                    start_year = 2022,
#                                    lot_area=0,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.00,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft= 2000000,
#                                    commercial_gross_sqft= 0,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=0,
#                                    avgUnitSize_residential=680,
#                                    avgUnitSize_commercial = 0,
#                                    avgUnitSize_manufacturing = 0,
#                                    avgUnitSize_community = 0,
#                                    residential_cost= 470,
#                                    residential_rent= 590, #per month, 1000
#                                    commercial_cost= 0,
#                                    commercial_rent= 0,
#                                    manufacturing_cost= 0,
#                                    manufacturing_rent=0,
#                                    community_cost= 0,
#                                    community_rent = 0,
#                                    hard_cost= 0,
#                                    soft_cost= 0,
#                                    land_cost= 0)


