import proforma.ProFormaForm as ProFormaForm
from statistics import mean

myUnits = mean([900,1000,1500]) #unit in sqft



# CarPark Legacy
# myProForma = ProFormaForm.ProForma(verbose= True,
#                                    exportToExcel= False,
#                                    yrs = 10,
#                                    start_year = 2022,
#                                    lot_area=637132,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft= 203979,
#                                    commercial_gross_sqft=485533,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=161845,
#                                    avgUnitSize_residential=680,
#                                    avgUnitSize_commercial=475,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=905,
#                                    residential_cost=470,
#                                    residential_rent=2471,
#                                    commercial_cost=400,
#                                    commercial_rent=19000,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=400,
#                                    community_rent=18100,
#                                    hard_cost=1009424171,
#                                    soft_cost=432610359,
#                                    land_cost=1)


#
# # Towers in the soup
# myProForma = ProFormaForm.ProForma(verbose= True,
#                                    exportToExcel= False,
#                                    yrs = 10,
#                                    start_year = 2022,
#                                    lot_area=0,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.15,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft= 1900000,
#                                    commercial_gross_sqft=100000,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=0,
#                                    avgUnitSize_residential=750,
#                                    avgUnitSize_commercial=3000,
#                                    avgUnitSize_manufacturing=0,
#                                    avgUnitSize_community=0,
#                                    residential_cost=375,
#                                    residential_rent=3600,
#                                    commercial_cost=700,
#                                    commercial_rent=285000,
#                                    manufacturing_cost=0,
#                                    manufacturing_rent=0,
#                                    community_cost=0,
#                                    community_rent=0,
#                                    hard_cost=0,
#                                    soft_cost=0,
#                                    land_cost=0)

# Air rights
myProForma = ProFormaForm.ProForma(verbose= True,
                                   exportToExcel= False,
                                   yrs = 10,
                                   start_year = 2022,
                                   lot_area=637132,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 203979,
                                   commercial_gross_sqft=485533,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft=161845,
                                   avgUnitSize_residential=680,
                                   avgUnitSize_commercial=475,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community=905,
                                   residential_cost=470,
                                   residential_rent=2471,
                                   commercial_cost=400,
                                   commercial_rent=19000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost=400,
                                   community_rent=18100,
                                   hard_cost=311,
                                   soft_cost=134,
                                   land_cost=1)

# myProForma = ProFormaForm.ProForma(verbose= True,
#                                    exportToExcel= False,
#                                    yrs = 10,
#                                    start_year = 2022,
#                                    lot_area=0,
#                                    equity = 0.70,
#                                    net_loss_factor= 0.00,
#                                    existingBuildingFloorArea=0,
#                                    existingBuildingPurchase=0,
#                                    residential_gross_sqft= 2000000,
#                                    commercial_gross_sqft= 0,
#                                    manufacturing_gross_sqft=0,
#                                    community_gross_sqft=0,
#                                    avgUnitSize_residential=680,
#                                    avgUnitSize_commercial = 0,
#                                    avgUnitSize_manufacturing = 0,
#                                    avgUnitSize_community = 0,
#                                    residential_cost= 470,
#                                    residential_rent= 590, #per month, 1000
#                                    commercial_cost= 0,
#                                    commercial_rent= 0,
#                                    manufacturing_cost= 0,
#                                    manufacturing_rent=0,
#                                    community_cost= 0,
#                                    community_rent = 0,
#                                    hard_cost= 0,
#                                    soft_cost= 0,
#                                    land_cost= 0)


