import proforma.ProFormaForm as ProFormaForm
from statistics import mean

##myAMI_1P1 = {'Affordable 1': ['Studio', 0.04,  400, 1150],
##          'Affordable 2': ['1-Bed', 0.14, 600, 1250],
##          'Affordable 3': ['2-Bed', 0.12, 800, 1500],
##          'Market 1': ['Studio', 0.10,  400, 3200],
##          'Market 2': ['1-Bed', 0.32, 600, 4000],
##          'Market 3': ['2-Bed', 0.28, 800, 5700],
##          }

myProFormaP1 = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P1)

myAMI_1P1rep = {'Affordable 1': ['Studio', 0.04,  400, 1150],
          'Affordable 2': ['1-Bed', 0.14, 600, 1250],
          'Affordable 3': ['2-Bed', 0.12, 800, 1500],
          'Market 1': ['Studio', 0.10,  400, 3200],
          'Market 2': ['1-Bed', 0.32, 600, 4000],
          'Market 3': ['2-Bed', 0.28, 800, 5700],
          }

myProFormaP1rep = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P1rep)

myAMI_1P2 = {'Affordable 1': ['Studio', 0.06,  400, 1150],
          'Affordable 2': ['1-Bed', 0.18, 600, 1250],
          'Affordable 3': ['2-Bed', 0.16, 800, 1500],
          'Market 1': ['Studio', 0.08,  400, 3200],
          'Market 2': ['1-Bed', 0.28, 600, 4000],
          'Market 3': ['2-Bed', 0.24, 800, 5700],
          }

myProFormaP2 = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 3,
                                   start_year = 2034,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 188000,
                                   commercial_gross_sqft= 49210,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P2)

myAMI_1P2rep = {'Affordable 1': ['Studio', 0.04,  400, 1150],
          'Affordable 2': ['1-Bed', 0.14, 600, 1250],
          'Affordable 3': ['2-Bed', 0.12, 800, 1500],
          'Market 1': ['Studio', 0.10,  400, 3200],
          'Market 2': ['1-Bed', 0.32, 600, 4000],
          'Market 3': ['2-Bed', 0.28, 800, 5700],
          }

myProFormaP2rep = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P2rep)

myAMI_1P3 = {'Affordable 1': ['Studio', 0.08,  400, 1150],
          'Affordable 2': ['1-Bed', 0.28, 600, 1250],
          'Affordable 3': ['2-Bed', 0.24, 800, 1500],
          'Market 1': ['Studio', 0.06,  400, 3200],
          'Market 2': ['1-Bed', 0.18, 600, 4000],
          'Market 3': ['2-Bed', 0.16, 800, 5700],
          }

myProFormaP3 = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P3)

myAMI_1P3rep = {'Affordable 1': ['Studio', 0.04,  400, 1150],
          'Affordable 2': ['1-Bed', 0.14, 600, 1250],
          'Affordable 3': ['2-Bed', 0.12, 800, 1500],
          'Market 1': ['Studio', 0.10,  400, 3200],
          'Market 2': ['1-Bed', 0.32, 600, 4000],
          'Market 3': ['2-Bed', 0.28, 800, 5700],
          }

myProFormaP3rep = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P3rep)

myAMI_1P4 = {'Affordable 1': ['Studio', 0.10,  400, 1150],
          'Affordable 2': ['1-Bed', 0.32, 600, 1250],
          'Affordable 3': ['2-Bed', 0.28, 800, 1500],
          'Market 1': ['Studio', 0.04,  400, 3200],
          'Market 2': ['1-Bed', 0.14, 600, 4000],
          'Market 3': ['2-Bed', 0.12, 800, 5700],
          }

myProFormaP4 = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P4)

myAMI_1P4rep = {'Affordable 1': ['Studio', 0.04,  400, 1150],
          'Affordable 2': ['1-Bed', 0.14, 600, 1250],
          'Affordable 3': ['2-Bed', 0.12, 800, 1500],
          'Market 1': ['Studio', 0.10,  400, 3200],
          'Market 2': ['1-Bed', 0.32, 600, 4000],
          'Market 3': ['2-Bed', 0.28, 800, 5700],
          }

myProFormaP4rep = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 7,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 400700,
                                   commercial_gross_sqft= 76944,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 8100,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 2000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 1500,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 275,
                                   commercial_rent= 120000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 275,
                                   community_rent= 60000,
                                   hard_cost=250,
                                   soft_cost=107,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1P4rep)