import proforma.ProFormaForm as ProFormaForm
from statistics import mean

myAMI_1 = { 80: ['Studio', 0.1,  400, 1150],
          70: ['1-Bed', 0.3, 600, 1250],
          60: ['2-Bed', 0.1, 800, 1500],
          'Marke 80': ['Studio', 0.2,  400, 3200],
          'Market 70': ['1-Bed', 0.1, 600, 4000],
          'Market 60': ['2-Bed', 0.2, 800, 5700],
          }

myProFormaPhase1 = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 10,
                                   start_year = 2022,
                                   lot_area=0,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 1170892,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 1900000,
                                   commercial_gross_sqft=100000,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft=0,
                                   avgUnitSize_residential=750,
                                   avgUnitSize_commercial=3000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community=0,
                                   residential_cost=375,
                                   residential_rent=3600,
                                   commercial_cost=700,
                                   commercial_rent=285000,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost=0,
                                   community_rent=0,
                                   hard_cost=0,
                                   soft_cost=0,
                                   land_cost=0,
                                   landscape_cost= 50,
                                   residential_AMI=myAMI_1)
