import proforma.ProFormaForm as ProFormaForm
from statistics import mean

myAMI_1 = {'Affordable 1': ['Studio', 0.07,  400, 1150],
          'Affordable 2': ['1-Bed', 0.23, 600, 1250],
          'Affordable 3': ['2-Bed', 0.2, 800, 1500],
          'Market 1': ['Studio', 0.07,  400, 3200],
          'Market 2': ['1-Bed', 0.23, 600, 4000],
          'Market 3': ['2-Bed', 0.2, 800, 5700],
          }

myProForma = ProFormaForm.ProForma(verbose= False,
                                   exportToExcel= False,
                                   yrs = 33,
                                   start_year = 2025,
                                   lot_area= 839831,
                                   equity = 0.70,
                                   net_loss_factor= 0.15,
                                   landscape_gross_sqft= 0,
                                   existingBuildingFloorArea=0,
                                   existingBuildingPurchase=0,
                                   residential_gross_sqft= 1239300,
                                   commercial_gross_sqft= 141150,
                                   manufacturing_gross_sqft=0,
                                   community_gross_sqft= 32400,
                                   avgUnitSize_residential= 600,
                                   avgUnitSize_commercial= 5000,
                                   avgUnitSize_manufacturing=0,
                                   avgUnitSize_community= 4000,
                                   residential_cost= 375,
                                   residential_rent= 2800,
                                   commercial_cost= 290,
                                   commercial_rent= 14200,
                                   manufacturing_cost=0,
                                   manufacturing_rent=0,
                                   community_cost= 290,
                                   community_rent= 9500,
                                   hard_cost=255.5,
                                   soft_cost=109.5,
                                   land_cost=1,
                                   landscape_cost=0,
                                   residential_AMI=myAMI_1)
